language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

#before_install:
# - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install numpy
  - sudo pip install scipy
  - pip install -r requirements-test.txt
  - python ./setup.py install

script:
  - py.test unittests
  - flake8 examples spynnaker_extra_pynn_models
  - flake8 unittests
  # TODO Add testing/style-checking of neural_modelling
