language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

#before_install:
# - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install numpy
  - sudo pip install scipy
  - pip install -r requirements-test.txt
  - pip install -r doc/doc_requirements.txt
  - python ./setup.py install

script:
  - py.test unittests
  - flake8 examples spynnaker_extra_pynn_models
  - flake8 unittests
  # TODO Add testing/style-checking of neural_modelling
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia
